import React from 'react'

export const  About=()=> {
    return (
        <div class="textCenter">
        <h1>"About application"</h1>
        <h5 className="py-2">All user pictures and data is fake and randomly 
        generated by open-source third-party service.</h5>
        </div>
    )
}
